// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
#include "Basis_HGrad_HexC2Basis.h"

const char *Basis_HGrad_HexC2Basis =
"basis[0] = 0.125 * (-1. + rr) * rr * (-1. + ss) * ss * (-1. + tt) * tt;\n"
"basis[1] = 0.125 * rr * (1. + rr) * (-1. + ss) * ss * (-1. + tt) * tt;\n"
"basis[2] = 0.125 * rr * (1. + rr) * ss * (1. + ss) * (-1. + tt) * tt;\n"
"basis[3] = 0.125 * (-1. + rr) * rr * ss * (1. + ss) * (-1. + tt) * tt;\n"
"basis[4] = 0.125 * (-1. + rr) * rr * (-1. + ss) * ss * tt * (1. + tt);\n"
"basis[5] = 0.125 * rr * (1. + rr) * (-1. + ss) * ss * tt * (1. + tt);\n"
"basis[6] = 0.125 * rr * (1. + rr) * ss * (1. + ss) * tt * (1. + tt);\n"
"basis[7] = 0.125 * (-1. + rr) * rr * ss * (1. + ss) * tt * (1. + tt);\n"
"\n"
"basis[8] = 0.25 * (1. - rr) * (1. + rr) * (-1. + ss) * ss * (-1. + tt) * tt;\n"
"basis[9] = 0.25 * rr * (1. + rr) * (1. - ss) * (1. + ss) * (-1. + tt) * tt;\n"
"basis[10] = 0.25 * (1. - rr) * (1. + rr) * ss * (1. + ss) * (-1. + tt) * tt;\n"
"basis[11] = 0.25 * (-1. + rr) * rr * (1. - ss) * (1. + ss) * (-1. + tt) * tt;\n"
"\n"
"basis[12] = 0.25 * (-1. + rr) * rr * (-1. + ss) * ss * (1. - tt) * (1. + tt);\n"
"basis[13] = 0.25 * rr * (1. + rr) * (-1. + ss) * ss * (1. - tt) * (1. + tt);\n"
"basis[14] = 0.25 * rr * (1. + rr) * ss * (1. + ss) * (1. - tt) * (1. + tt);\n"
"basis[15] = 0.25 * (-1. + rr) * rr * ss * (1. + ss) * (1. - tt) * (1. + tt);\n"
"\n"
"basis[16] = 0.25 * (1. - rr) * (1. + rr) * (-1. + ss) * ss * tt * (1. + tt);\n"
"basis[17] = 0.25 * rr * (1. + rr) * (1. - ss) * (1. + ss) * tt * (1. + tt);\n"
"basis[18] = 0.25 * (1. - rr) * (1. + rr) * ss * (1. + ss) * tt * (1. + tt);\n"
"basis[19] = 0.25 * (-1. + rr) * rr * (1. - ss) * (1. + ss) * tt * (1. + tt);\n"
"\n"
"basis[20] = (1. - rr) * (1. + rr) * (1. - ss) * (1. + ss) * (1. - tt) * (1. + tt);\n"
"\n"
"basis[21] = 0.5 * (1. - rr) * (1. + rr) * (1. - ss) * (1. + ss) * (-1. + tt) * tt;\n"
"basis[22] = 0.5 * (1. - rr) * (1. + rr) * (1. - ss) * (1. + ss) * tt * (1. + tt);\n"
"basis[23] = 0.5 * (-1. + rr) * rr * (1. - ss) * (1. + ss) * (1. - tt) * (1. + tt);\n"
"basis[24] = 0.5 * rr * (1. + rr) * (1. - ss) * (1. + ss) * (1. - tt) * (1. + tt);\n"
"basis[25] = 0.5 * (1. - rr) * (1. + rr) * (-1. + ss) * ss * (1. - tt) * (1. + tt);\n"
"basis[26] = 0.5 * (1. - rr) * (1. + rr) * ss * (1. + ss) * (1. - tt) * (1. + tt);\n"
"";
