// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
#include "Basis_HGrad_TetC2Gradient.h"

const char *Basis_HGrad_TetC2Gradient =
"basisGradient[0] = -3. + 4. * rr + 4. * ss + 4. * tt;\n"
"basisGradient[1] = -3. + 4. * rr + 4. * ss + 4. * tt;\n"
"basisGradient[2] = -3. + 4. * rr + 4. * ss + 4. * tt;\n"
"\n"
"basisGradient[3] = -1. + 4. * rr;\n"
"basisGradient[4] = 0.;\n"
"basisGradient[5] = 0.;\n"
"\n"
"basisGradient[6] = 0.;\n"
"basisGradient[7] = -1. + 4. * ss;\n"
"basisGradient[8] = 0.;\n"
"\n"
"basisGradient[9] = 0.;\n"
"basisGradient[10] = 0.;\n"
"basisGradient[11] = -1. + 4. * tt;\n"
"\n"
"basisGradient[12] = -4. * (-1. + 2 * rr + ss + tt);\n"
"basisGradient[13] = -4. * rr;\n"
"basisGradient[14] = -4. * rr;\n"
"\n"
"basisGradient[15] = 4. * ss;\n"
"basisGradient[16] = 4. * rr;\n"
"basisGradient[17] = 0.;\n"
"\n"
"basisGradient[18] = -4. * ss;\n"
"basisGradient[19] = -4. * (-1. + rr + 2 * ss + tt);\n"
"basisGradient[20] = -4. * ss;\n"
"\n"
"basisGradient[21] = -4. * tt;\n"
"basisGradient[22] = -4. * tt;\n"
"basisGradient[23] = -4. * (-1. + rr + ss + 2 * tt);\n"
"\n"
"basisGradient[24] = 4. * tt;\n"
"basisGradient[25] = 0.;\n"
"basisGradient[26] = 4. * rr;\n"
"\n"
"basisGradient[27] = 0.;\n"
"basisGradient[28] = 4. * tt;\n"
"basisGradient[29] = 4. * ss;\n"
"";
