// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
#include "vtkPolyData2DFS.h"

const char *vtkPolyData2DFS =
"//VTK::System::Dec\n"
"\n"
"// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen\n"
"// SPDX-License-Identifier: BSD-3-Clause\n"
"\n"
"uniform int PrimitiveIDOffset;\n"
"\n"
"// Custom uniforms\n"
"//VTK::CustomUniforms::Dec\n"
"\n"
"// Texture coordinates\n"
"//VTK::TCoord::Dec\n"
"\n"
"// Scalar coloring\n"
"//VTK::Color::Dec\n"
"\n"
"// Depth Peeling\n"
"//VTK::DepthPeeling::Dec\n"
"\n"
"// picking support\n"
"//VTK::Picking::Dec\n"
"\n"
"// the output of this shader\n"
"//VTK::Output::Dec\n"
"\n"
"// Apple Bug\n"
"//VTK::PrimID::Dec\n"
"\n"
"void main()\n"
"{\n"
"  // Apple Bug\n"
"  //VTK::PrimID::Impl\n"
"\n"
"  //VTK::Color::Impl\n"
"  //VTK::TCoord::Impl\n"
"\n"
"  //VTK::DepthPeeling::Impl\n"
"  //VTK::Picking::Impl\n"
"\n"
"  if (gl_FragData[0].a <= 0.0)\n"
"    {\n"
"    discard;\n"
"    }\n"
"}\n"
"";
