# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ospray::ospray ospray::ospray_module_cpu ospray::ospray_module_gpu_kernels ospray::ospray_module_gpu ospray::ospray_sdk ospray::ospray_module_denoiser ospray::ospray_mpi_common ospray::ospray_module_mpi_offload ospray::ospray_module_mpi_distributed_cpu ospray::ospray_module_mpi_distributed_gpu_kernels ospray::ospray_module_mpi_distributed_gpu ospray::ospray_imgui ospray::ospray_testing)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target ospray::ospray
add_library(ospray::ospray SHARED IMPORTED)

set_target_properties(ospray::ospray PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target ospray::ospray_module_cpu
add_library(ospray::ospray_module_cpu SHARED IMPORTED)

set_target_properties(ospray::ospray_module_cpu PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TILE_SIZE=64;MAX_TILE_SIZE=64;SYCL_EXTERNAL=;OSPRAY_GLOBAL=;OSPRAY_ENABLE_VOLUMES"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ospray/SDK;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ospray::ospray;rkcommon::rkcommon"
)

# Create imported target ospray::ospray_module_gpu_kernels
add_library(ospray::ospray_module_gpu_kernels INTERFACE IMPORTED)

set_target_properties(ospray::ospray_module_gpu_kernels PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TILE_SIZE=64;MAX_TILE_SIZE=64;RKCOMMON_NO_SIMD;OSPRAY_TARGET_SYCL;__SYCL_USE_NON_VARIADIC_SPIRV_OCL_PRINTF__;OSPRAY_BEGIN_ISPC_NAMESPACE=namespace ispc{;OSPRAY_END_ISPC_NAMESPACE=};OSPRAY_GLOBAL=static;_ALLOW_KEYWORD_MACROS;uniform=;varying=;unmasked=;export=;rtcIntersectV=rtcIntersect1;rtcOccludedV=rtcOccluded1;rtcInterpolateV1=rtcInterpolate1;vklComputeSampleV=vklComputeSample;vklComputeGradientV=vklComputeGradient;vklInitIntervalIteratorV=vklInitIntervalIterator;vklIterateIntervalV=vklIterateInterval;vklInitHitIteratorV=vklInitHitIterator;vklIterateHitV=vklIterateHit;programCount=1;programIndex=0;OSPRAY_ENABLE_VOLUMES"
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-fsycl;-fsycl-unnamed-lambda;-Xclang;-fsycl-allow-func-ptr;-Wno-mismatched-tags;-Wno-pessimizing-move;-Wno-reorder;-Wno-unneeded-internal-declaration;-Wno-delete-non-abstract-non-virtual-dtor;-Wno-dangling-field;-Wno-unknown-pragmas;-Wno-logical-op-parentheses"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ospray/SDK;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ospray::ospray;rkcommon::rkcommon"
  INTERFACE_LINK_OPTIONS "-fsycl;-Xsycl-target-backend=spir64;-cl-intel-greater-than-4GB-buffer-required -options \"-cl-intel-force-global-mem-allocation -cl-intel-no-local-to-generic -O2 -ze-opt-large-register-file -igc_opts='VISAOptions=-scratchAllocForStackInKB 128'\""
)

# Create imported target ospray::ospray_module_gpu
add_library(ospray::ospray_module_gpu SHARED IMPORTED)

set_target_properties(ospray::ospray_module_gpu PROPERTIES
  INTERFACE_LINK_LIBRARIES "ospray::ospray_module_gpu_kernels"
)

# Create imported target ospray::ospray_sdk
add_library(ospray::ospray_sdk INTERFACE IMPORTED)

set_target_properties(ospray::ospray_sdk PROPERTIES
  INTERFACE_LINK_LIBRARIES "ospray::ospray;rkcommon::rkcommon"
)

# Create imported target ospray::ospray_module_denoiser
add_library(ospray::ospray_module_denoiser SHARED IMPORTED)

# Create imported target ospray::ospray_mpi_common
add_library(ospray::ospray_mpi_common SHARED IMPORTED)

set_target_properties(ospray::ospray_mpi_common PROPERTIES
  INTERFACE_LINK_LIBRARIES "rkcommon::rkcommon;ospray::ospray;MPI::MPI_CXX"
)

# Create imported target ospray::ospray_module_mpi_offload
add_library(ospray::ospray_module_mpi_offload SHARED IMPORTED)

set_target_properties(ospray::ospray_module_mpi_offload PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OSP_MPI_COMPRESSION_THRESHOLD=16;OBJECTFACTORY_IMPORT"
)

# Create imported target ospray::ospray_module_mpi_distributed_cpu
add_library(ospray::ospray_module_mpi_distributed_cpu SHARED IMPORTED)

# Create imported target ospray::ospray_module_mpi_distributed_gpu_kernels
add_library(ospray::ospray_module_mpi_distributed_gpu_kernels INTERFACE IMPORTED)

set_target_properties(ospray::ospray_module_mpi_distributed_gpu_kernels PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ospray::ospray_module_gpu_kernels>"
)

# Create imported target ospray::ospray_module_mpi_distributed_gpu
add_library(ospray::ospray_module_mpi_distributed_gpu SHARED IMPORTED)

set_target_properties(ospray::ospray_module_mpi_distributed_gpu PROPERTIES
  INTERFACE_LINK_LIBRARIES "ospray::ospray_module_gpu_kernels;ospray::ospray_module_mpi_distributed_gpu_kernels"
)

# Create imported target ospray::ospray_imgui
add_library(ospray::ospray_imgui SHARED IMPORTED)

set_target_properties(ospray::ospray_imgui PROPERTIES
  INTERFACE_LINK_LIBRARIES "glfw;opengl32;glu32"
)

# Create imported target ospray::ospray_testing
add_library(ospray::ospray_testing SHARED IMPORTED)

set_target_properties(ospray::ospray_testing PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ospray/ospray_testing"
  INTERFACE_LINK_LIBRARIES "ospray::ospray_sdk"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/ospray_Exports-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
