if (NOT DEFINED "Qt6_DIR" OR NOT Qt6_DIR)
  set("Qt6_DIR" "D:/Qt/6.8.3/msvc2022_64/lib/cmake/Qt6" CACHE PATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
if (NOT DEFINED "ospray_DIR" OR NOT ospray_DIR)
  set("ospray_DIR" "D:\cybermed\daddy\dependency\ospray-3.2.0.x86_64.windows\lib\cmake\ospray-3.2.0" CACHE PATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
if (NOT DEFINED "OpenImageDenoise_DIR" OR NOT OpenImageDenoise_DIR)
  set("OpenImageDenoise_DIR" "D:\cybermed\daddy\dependency\oidn-2.3.1.x64.windows\lib\cmake\OpenImageDenoise-2.3.1" CACHE PATH "Third-party helper setting from ${CMAKE_FIND_PACKAGE_NAME}")
endif ()
