
#ifndef VTKGUISUPPORTQTQUICK_EXPORT_H
#define VTKGUISUPPORTQTQUICK_EXPORT_H

#ifdef VTKGUISUPPORTQTQUICK_STATIC_DEFINE
#  define VTKGUISUPPORTQTQUICK_EXPORT
#  define VTKGUISUPPORTQTQUICK_NO_EXPORT
#else
#  ifndef VTKGUISUPPORTQTQUICK_EXPORT
#    ifdef GUISupportQtQuick_EXPORTS
        /* We are building this library */
#      define VTKGUISUPPORTQTQUICK_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKGUISUPPORTQTQUICK_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKGUISUPPORTQTQUICK_NO_EXPORT
#    define VTKGUISUPPORTQTQUICK_NO_EXPORT 
#  endif
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED
#  define VTKGUISUPPORTQTQUICK_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT
#  define VTKGUISUPPORTQTQUICK_DEPRECATED_EXPORT VTKGUISUPPORTQTQUICK_EXPORT VTKGUISUPPORTQTQUICK_DEPRECATED
#endif

#ifndef VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT
#  define VTKGUISUPPORTQTQUICK_DEPRECATED_NO_EXPORT VTKGUISUPPORTQTQUICK_NO_EXPORT VTKGUISUPPORTQTQUICK_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKGUISUPPORTQTQUICK_NO_DEPRECATED
#    define VTKGUISUPPORTQTQUICK_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkGUISupportQtQuickModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKGUISUPPORTQTQUICK_EXPORT_H */
