// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
#include "raycastervs.h"

const char *raycastervs =
"//VTK::System::Dec\n"
"\n"
"// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen\n"
"// SPDX-License-Identifier: BSD-3-Clause\n"
"\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"///\n"
"/// Uniforms, attributes, and globals\n"
"///\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"//VTK::CustomUniforms::Dec\n"
"\n"
"//VTK::Base::Dec\n"
"\n"
"//VTK::Termination::Dec\n"
"\n"
"//VTK::Cropping::Dec\n"
"\n"
"//VTK::Shading::Dec\n"
"\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"///\n"
"/// Inputs\n"
"///\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"in vec3 in_vertexPos;\n"
"\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"///\n"
"/// Outputs\n"
"///\n"
"//////////////////////////////////////////////////////////////////////////////\n"
"/// 3D texture coordinates for texture lookup in the fragment shader\n"
"out vec3 ip_textureCoords;\n"
"out vec3 ip_vertexPos;\n"
"\n"
"void main()\n"
"{\n"
"  /// Get clipspace position\n"
"  //VTK::ComputeClipPos::Impl\n"
"\n"
"  /// Compute texture coordinates\n"
"  //VTK::ComputeTextureCoords::Impl\n"
"\n"
"  /// Copy incoming vertex position for the fragment shader\n"
"  ip_vertexPos = in_vertexPos;\n"
"}\n"
"";
