# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS DCMTK::config DCMTK::ofstd DCMTK::oflog DCMTK::oficonv DCMTK::dcmdata DCMTK::i2d DCMTK::dcmxml DCMTK::dcmimgle DCMTK::dcmimage DCMTK::dcmjpeg DCMTK::ijg8 DCMTK::ijg12 DCMTK::ijg16 DCMTK::dcmjpls DCMTK::dcmtkcharls DCMTK::dcmtls DCMTK::dcmnet DCMTK::dcmsr DCMTK::cmr DCMTK::dcmdsig DCMTK::dcmwlm DCMTK::dcmqrdb DCMTK::dcmpstat DCMTK::dcmrt DCMTK::dcmiod DCMTK::dcmfg DCMTK::dcmseg DCMTK::dcmtract DCMTK::dcmpmap DCMTK::dcmect DCMTK::DCMTK)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target DCMTK::config
add_library(DCMTK::config INTERFACE IMPORTED)

set_target_properties(DCMTK::config PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/config/include"
)

# Create imported target DCMTK::ofstd
add_library(DCMTK::ofstd SHARED IMPORTED)

set_target_properties(DCMTK::ofstd PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/ofstd/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::config;iphlpapi;ws2_32;netapi32;wsock32;DCMTK::oficonv"
)

# Create imported target DCMTK::oflog
add_library(DCMTK::oflog SHARED IMPORTED)

set_target_properties(DCMTK::oflog PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/oflog/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd"
)

# Create imported target DCMTK::oficonv
add_library(DCMTK::oficonv SHARED IMPORTED)

set_target_properties(DCMTK::oficonv PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/oficonv/include"
  INTERFACE_LINK_LIBRARIES "iphlpapi;ws2_32;netapi32;wsock32"
)

# Create imported target DCMTK::dcmdata
add_library(DCMTK::dcmdata SHARED IMPORTED)

set_target_properties(DCMTK::dcmdata PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmdata/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::i2d
add_library(DCMTK::i2d SHARED IMPORTED)

set_target_properties(DCMTK::i2d PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmdata/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmxml;DCMTK::dcmdata"
)

# Create imported target DCMTK::dcmxml
add_library(DCMTK::dcmxml SHARED IMPORTED)

set_target_properties(DCMTK::dcmxml PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmdata/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmimgle
add_library(DCMTK::dcmimgle SHARED IMPORTED)

set_target_properties(DCMTK::dcmimgle PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmimgle/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata"
)

# Create imported target DCMTK::dcmimage
add_library(DCMTK::dcmimage SHARED IMPORTED)

set_target_properties(DCMTK::dcmimage PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmimage/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmimgle"
)

# Create imported target DCMTK::dcmjpeg
add_library(DCMTK::dcmjpeg SHARED IMPORTED)

set_target_properties(DCMTK::dcmjpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpeg/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmimgle;DCMTK::dcmimage;DCMTK::ijg8;DCMTK::ijg12;DCMTK::ijg16"
)

# Create imported target DCMTK::ijg8
add_library(DCMTK::ijg8 SHARED IMPORTED)

set_target_properties(DCMTK::ijg8 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpeg/include"
)

# Create imported target DCMTK::ijg12
add_library(DCMTK::ijg12 SHARED IMPORTED)

set_target_properties(DCMTK::ijg12 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpeg/include"
)

# Create imported target DCMTK::ijg16
add_library(DCMTK::ijg16 SHARED IMPORTED)

set_target_properties(DCMTK::ijg16 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpeg/include"
)

# Create imported target DCMTK::dcmjpls
add_library(DCMTK::dcmjpls SHARED IMPORTED)

set_target_properties(DCMTK::dcmjpls PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpls/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmimgle;DCMTK::dcmimage;DCMTK::dcmtkcharls"
)

# Create imported target DCMTK::dcmtkcharls
add_library(DCMTK::dcmtkcharls SHARED IMPORTED)

set_target_properties(DCMTK::dcmtkcharls PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmjpls/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmtls
add_library(DCMTK::dcmtls SHARED IMPORTED)

set_target_properties(DCMTK::dcmtls PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmtls/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::dcmdata;DCMTK::dcmnet"
)

# Create imported target DCMTK::dcmnet
add_library(DCMTK::dcmnet SHARED IMPORTED)

set_target_properties(DCMTK::dcmnet PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmnet/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata"
)

# Create imported target DCMTK::dcmsr
add_library(DCMTK::dcmsr SHARED IMPORTED)

set_target_properties(DCMTK::dcmsr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmsr/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmimgle;DCMTK::dcmimage"
)

# Create imported target DCMTK::cmr
add_library(DCMTK::cmr SHARED IMPORTED)

set_target_properties(DCMTK::cmr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmsr/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmsr"
)

# Create imported target DCMTK::dcmdsig
add_library(DCMTK::dcmdsig SHARED IMPORTED)

set_target_properties(DCMTK::dcmdsig PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmsign/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::dcmdata"
)

# Create imported target DCMTK::dcmwlm
add_library(DCMTK::dcmwlm SHARED IMPORTED)

set_target_properties(DCMTK::dcmwlm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmwlm/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::dcmdata;DCMTK::dcmnet"
)

# Create imported target DCMTK::dcmqrdb
add_library(DCMTK::dcmqrdb SHARED IMPORTED)

set_target_properties(DCMTK::dcmqrdb PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmqrdb/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::dcmdata;DCMTK::dcmnet"
)

# Create imported target DCMTK::dcmpstat
add_library(DCMTK::dcmpstat SHARED IMPORTED)

set_target_properties(DCMTK::dcmpstat PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmpstat/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmiod;DCMTK::dcmimgle;DCMTK::dcmimage;DCMTK::dcmnet;DCMTK::dcmdsig;DCMTK::dcmtls;DCMTK::dcmsr;DCMTK::dcmqrdb"
)

# Create imported target DCMTK::dcmrt
add_library(DCMTK::dcmrt SHARED IMPORTED)

set_target_properties(DCMTK::dcmrt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmrt/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::ofstd;DCMTK::oflog;DCMTK::dcmdata;DCMTK::dcmimgle"
)

# Create imported target DCMTK::dcmiod
add_library(DCMTK::dcmiod SHARED IMPORTED)

set_target_properties(DCMTK::dcmiod PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmiod/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmfg
add_library(DCMTK::dcmfg SHARED IMPORTED)

set_target_properties(DCMTK::dcmfg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmfg/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmiod;DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmseg
add_library(DCMTK::dcmseg SHARED IMPORTED)

set_target_properties(DCMTK::dcmseg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmseg/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmfg;DCMTK::dcmiod;DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmtract
add_library(DCMTK::dcmtract SHARED IMPORTED)

set_target_properties(DCMTK::dcmtract PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmtract/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmiod;DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmpmap
add_library(DCMTK::dcmpmap SHARED IMPORTED)

set_target_properties(DCMTK::dcmpmap PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmpmap/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmfg;DCMTK::dcmiod;DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::dcmect
add_library(DCMTK::dcmect SHARED IMPORTED)

set_target_properties(DCMTK::dcmect PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/dcmect/include"
  INTERFACE_LINK_LIBRARIES "DCMTK::dcmfg;DCMTK::dcmiod;DCMTK::dcmdata;DCMTK::ofstd;DCMTK::oflog"
)

# Create imported target DCMTK::DCMTK
add_library(DCMTK::DCMTK INTERFACE IMPORTED)

set_target_properties(DCMTK::DCMTK PROPERTIES
  INTERFACE_LINK_LIBRARIES "DCMTK::config;DCMTK::ofstd;DCMTK::oflog;DCMTK::oficonv;DCMTK::dcmdata;DCMTK::i2d;DCMTK::dcmxml;DCMTK::dcmimgle;DCMTK::dcmimage;DCMTK::dcmjpeg;DCMTK::ijg8;DCMTK::ijg12;DCMTK::ijg16;DCMTK::dcmjpls;DCMTK::dcmtkcharls;DCMTK::dcmtls;DCMTK::dcmnet;DCMTK::dcmsr;DCMTK::cmr;DCMTK::dcmdsig;DCMTK::dcmwlm;DCMTK::dcmqrdb;DCMTK::dcmpstat;DCMTK::dcmrt;DCMTK::dcmiod;DCMTK::dcmfg;DCMTK::dcmseg;DCMTK::dcmtract;DCMTK::dcmpmap;DCMTK::dcmect"
)

# Import target "DCMTK::ofstd" for configuration "Debug"
set_property(TARGET DCMTK::ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::ofstd PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/ofstd.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/ofstd.dll"
  )

# Import target "DCMTK::oflog" for configuration "Debug"
set_property(TARGET DCMTK::oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::oflog PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/oflog.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/oflog.dll"
  )

# Import target "DCMTK::oficonv" for configuration "Debug"
set_property(TARGET DCMTK::oficonv APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::oficonv PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/oficonv.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/oficonv.dll"
  )

# Import target "DCMTK::dcmdata" for configuration "Debug"
set_property(TARGET DCMTK::dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmdata PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmdata.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmdata.dll"
  )

# Import target "DCMTK::i2d" for configuration "Debug"
set_property(TARGET DCMTK::i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::i2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/i2d.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/i2d.dll"
  )

# Import target "DCMTK::dcmxml" for configuration "Debug"
set_property(TARGET DCMTK::dcmxml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmxml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmxml.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmxml.dll"
  )

# Import target "DCMTK::dcmimgle" for configuration "Debug"
set_property(TARGET DCMTK::dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmimgle PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmimgle.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmimgle.dll"
  )

# Import target "DCMTK::dcmimage" for configuration "Debug"
set_property(TARGET DCMTK::dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmimage PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmimage.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmimage.dll"
  )

# Import target "DCMTK::dcmjpeg" for configuration "Debug"
set_property(TARGET DCMTK::dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmjpeg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmjpeg.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmjpeg.dll"
  )

# Import target "DCMTK::ijg8" for configuration "Debug"
set_property(TARGET DCMTK::ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::ijg8 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/ijg8.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/ijg8.dll"
  )

# Import target "DCMTK::ijg12" for configuration "Debug"
set_property(TARGET DCMTK::ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::ijg12 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/ijg12.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/ijg12.dll"
  )

# Import target "DCMTK::ijg16" for configuration "Debug"
set_property(TARGET DCMTK::ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::ijg16 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/ijg16.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/ijg16.dll"
  )

# Import target "DCMTK::dcmjpls" for configuration "Debug"
set_property(TARGET DCMTK::dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmjpls PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmjpls.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmjpls.dll"
  )

# Import target "DCMTK::dcmtkcharls" for configuration "Debug"
set_property(TARGET DCMTK::dcmtkcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmtkcharls PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmtkcharls.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmtkcharls.dll"
  )

# Import target "DCMTK::dcmtls" for configuration "Debug"
set_property(TARGET DCMTK::dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmtls PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmtls.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmtls.dll"
  )

# Import target "DCMTK::dcmnet" for configuration "Debug"
set_property(TARGET DCMTK::dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmnet PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmnet.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmnet.dll"
  )

# Import target "DCMTK::dcmsr" for configuration "Debug"
set_property(TARGET DCMTK::dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmsr PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmsr.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmsr.dll"
  )

# Import target "DCMTK::cmr" for configuration "Debug"
set_property(TARGET DCMTK::cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::cmr PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/cmr.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/cmr.dll"
  )

# Import target "DCMTK::dcmdsig" for configuration "Debug"
set_property(TARGET DCMTK::dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmdsig PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmdsig.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmdsig.dll"
  )

# Import target "DCMTK::dcmwlm" for configuration "Debug"
set_property(TARGET DCMTK::dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmwlm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmwlm.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmwlm.dll"
  )

# Import target "DCMTK::dcmqrdb" for configuration "Debug"
set_property(TARGET DCMTK::dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmqrdb PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmqrdb.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmqrdb.dll"
  )

# Import target "DCMTK::dcmpstat" for configuration "Debug"
set_property(TARGET DCMTK::dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmpstat PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmpstat.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmpstat.dll"
  )

# Import target "DCMTK::dcmrt" for configuration "Debug"
set_property(TARGET DCMTK::dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmrt PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmrt.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmrt.dll"
  )

# Import target "DCMTK::dcmiod" for configuration "Debug"
set_property(TARGET DCMTK::dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmiod PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmiod.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmiod.dll"
  )

# Import target "DCMTK::dcmfg" for configuration "Debug"
set_property(TARGET DCMTK::dcmfg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmfg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmfg.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmfg.dll"
  )

# Import target "DCMTK::dcmseg" for configuration "Debug"
set_property(TARGET DCMTK::dcmseg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmseg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmseg.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmseg.dll"
  )

# Import target "DCMTK::dcmtract" for configuration "Debug"
set_property(TARGET DCMTK::dcmtract APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmtract PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmtract.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmtract.dll"
  )

# Import target "DCMTK::dcmpmap" for configuration "Debug"
set_property(TARGET DCMTK::dcmpmap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmpmap PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmpmap.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmpmap.dll"
  )

# Import target "DCMTK::dcmect" for configuration "Debug"
set_property(TARGET DCMTK::dcmect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DCMTK::dcmect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Debug/dcmect.lib"
  IMPORTED_LOCATION_DEBUG "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Debug/dcmect.dll"
  )

# Import target "DCMTK::ofstd" for configuration "Release"
set_property(TARGET DCMTK::ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::ofstd PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/ofstd.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/ofstd.dll"
  )

# Import target "DCMTK::oflog" for configuration "Release"
set_property(TARGET DCMTK::oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::oflog PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/oflog.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/oflog.dll"
  )

# Import target "DCMTK::oficonv" for configuration "Release"
set_property(TARGET DCMTK::oficonv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::oficonv PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/oficonv.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/oficonv.dll"
  )

# Import target "DCMTK::dcmdata" for configuration "Release"
set_property(TARGET DCMTK::dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmdata PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmdata.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmdata.dll"
  )

# Import target "DCMTK::i2d" for configuration "Release"
set_property(TARGET DCMTK::i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::i2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/i2d.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/i2d.dll"
  )

# Import target "DCMTK::dcmxml" for configuration "Release"
set_property(TARGET DCMTK::dcmxml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmxml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmxml.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmxml.dll"
  )

# Import target "DCMTK::dcmimgle" for configuration "Release"
set_property(TARGET DCMTK::dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmimgle PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmimgle.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmimgle.dll"
  )

# Import target "DCMTK::dcmimage" for configuration "Release"
set_property(TARGET DCMTK::dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmimage PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmimage.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmimage.dll"
  )

# Import target "DCMTK::dcmjpeg" for configuration "Release"
set_property(TARGET DCMTK::dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmjpeg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmjpeg.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmjpeg.dll"
  )

# Import target "DCMTK::ijg8" for configuration "Release"
set_property(TARGET DCMTK::ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::ijg8 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/ijg8.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/ijg8.dll"
  )

# Import target "DCMTK::ijg12" for configuration "Release"
set_property(TARGET DCMTK::ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::ijg12 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/ijg12.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/ijg12.dll"
  )

# Import target "DCMTK::ijg16" for configuration "Release"
set_property(TARGET DCMTK::ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::ijg16 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/ijg16.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/ijg16.dll"
  )

# Import target "DCMTK::dcmjpls" for configuration "Release"
set_property(TARGET DCMTK::dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmjpls PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmjpls.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmjpls.dll"
  )

# Import target "DCMTK::dcmtkcharls" for configuration "Release"
set_property(TARGET DCMTK::dcmtkcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmtkcharls PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmtkcharls.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmtkcharls.dll"
  )

# Import target "DCMTK::dcmtls" for configuration "Release"
set_property(TARGET DCMTK::dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmtls PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmtls.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmtls.dll"
  )

# Import target "DCMTK::dcmnet" for configuration "Release"
set_property(TARGET DCMTK::dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmnet PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmnet.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmnet.dll"
  )

# Import target "DCMTK::dcmsr" for configuration "Release"
set_property(TARGET DCMTK::dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmsr PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmsr.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmsr.dll"
  )

# Import target "DCMTK::cmr" for configuration "Release"
set_property(TARGET DCMTK::cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::cmr PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/cmr.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/cmr.dll"
  )

# Import target "DCMTK::dcmdsig" for configuration "Release"
set_property(TARGET DCMTK::dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmdsig PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmdsig.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmdsig.dll"
  )

# Import target "DCMTK::dcmwlm" for configuration "Release"
set_property(TARGET DCMTK::dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmwlm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmwlm.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmwlm.dll"
  )

# Import target "DCMTK::dcmqrdb" for configuration "Release"
set_property(TARGET DCMTK::dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmqrdb PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmqrdb.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmqrdb.dll"
  )

# Import target "DCMTK::dcmpstat" for configuration "Release"
set_property(TARGET DCMTK::dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmpstat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmpstat.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmpstat.dll"
  )

# Import target "DCMTK::dcmrt" for configuration "Release"
set_property(TARGET DCMTK::dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmrt PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmrt.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmrt.dll"
  )

# Import target "DCMTK::dcmiod" for configuration "Release"
set_property(TARGET DCMTK::dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmiod PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmiod.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmiod.dll"
  )

# Import target "DCMTK::dcmfg" for configuration "Release"
set_property(TARGET DCMTK::dcmfg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmfg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmfg.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmfg.dll"
  )

# Import target "DCMTK::dcmseg" for configuration "Release"
set_property(TARGET DCMTK::dcmseg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmseg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmseg.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmseg.dll"
  )

# Import target "DCMTK::dcmtract" for configuration "Release"
set_property(TARGET DCMTK::dcmtract APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmtract PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmtract.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmtract.dll"
  )

# Import target "DCMTK::dcmpmap" for configuration "Release"
set_property(TARGET DCMTK::dcmpmap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmpmap PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmpmap.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmpmap.dll"
  )

# Import target "DCMTK::dcmect" for configuration "Release"
set_property(TARGET DCMTK::dcmect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DCMTK::dcmect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/Release/dcmect.lib"
  IMPORTED_LOCATION_RELEASE "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/Release/dcmect.dll"
  )

# Import target "DCMTK::ofstd" for configuration "MinSizeRel"
set_property(TARGET DCMTK::ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::ofstd PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/ofstd.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/ofstd.dll"
  )

# Import target "DCMTK::oflog" for configuration "MinSizeRel"
set_property(TARGET DCMTK::oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::oflog PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/oflog.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/oflog.dll"
  )

# Import target "DCMTK::oficonv" for configuration "MinSizeRel"
set_property(TARGET DCMTK::oficonv APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::oficonv PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/oficonv.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/oficonv.dll"
  )

# Import target "DCMTK::dcmdata" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmdata PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmdata.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmdata.dll"
  )

# Import target "DCMTK::i2d" for configuration "MinSizeRel"
set_property(TARGET DCMTK::i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::i2d PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/i2d.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/i2d.dll"
  )

# Import target "DCMTK::dcmxml" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmxml APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmxml PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmxml.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmxml.dll"
  )

# Import target "DCMTK::dcmimgle" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmimgle PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmimgle.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmimgle.dll"
  )

# Import target "DCMTK::dcmimage" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmimage PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmimage.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmimage.dll"
  )

# Import target "DCMTK::dcmjpeg" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmjpeg PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmjpeg.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmjpeg.dll"
  )

# Import target "DCMTK::ijg8" for configuration "MinSizeRel"
set_property(TARGET DCMTK::ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::ijg8 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/ijg8.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/ijg8.dll"
  )

# Import target "DCMTK::ijg12" for configuration "MinSizeRel"
set_property(TARGET DCMTK::ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::ijg12 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/ijg12.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/ijg12.dll"
  )

# Import target "DCMTK::ijg16" for configuration "MinSizeRel"
set_property(TARGET DCMTK::ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::ijg16 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/ijg16.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/ijg16.dll"
  )

# Import target "DCMTK::dcmjpls" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmjpls PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmjpls.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmjpls.dll"
  )

# Import target "DCMTK::dcmtkcharls" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmtkcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmtkcharls PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmtkcharls.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmtkcharls.dll"
  )

# Import target "DCMTK::dcmtls" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmtls PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmtls.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmtls.dll"
  )

# Import target "DCMTK::dcmnet" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmnet PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmnet.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmnet.dll"
  )

# Import target "DCMTK::dcmsr" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmsr PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmsr.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmsr.dll"
  )

# Import target "DCMTK::cmr" for configuration "MinSizeRel"
set_property(TARGET DCMTK::cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::cmr PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/cmr.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/cmr.dll"
  )

# Import target "DCMTK::dcmdsig" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmdsig PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmdsig.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmdsig.dll"
  )

# Import target "DCMTK::dcmwlm" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmwlm PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmwlm.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmwlm.dll"
  )

# Import target "DCMTK::dcmqrdb" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmqrdb PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmqrdb.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmqrdb.dll"
  )

# Import target "DCMTK::dcmpstat" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmpstat PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmpstat.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmpstat.dll"
  )

# Import target "DCMTK::dcmrt" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmrt PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmrt.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmrt.dll"
  )

# Import target "DCMTK::dcmiod" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmiod PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmiod.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmiod.dll"
  )

# Import target "DCMTK::dcmfg" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmfg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmfg PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmfg.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmfg.dll"
  )

# Import target "DCMTK::dcmseg" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmseg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmseg PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmseg.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmseg.dll"
  )

# Import target "DCMTK::dcmtract" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmtract APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmtract PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmtract.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmtract.dll"
  )

# Import target "DCMTK::dcmpmap" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmpmap APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmpmap PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmpmap.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmpmap.dll"
  )

# Import target "DCMTK::dcmect" for configuration "MinSizeRel"
set_property(TARGET DCMTK::dcmect APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DCMTK::dcmect PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/MinSizeRel/dcmect.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/MinSizeRel/dcmect.dll"
  )

# Import target "DCMTK::ofstd" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::ofstd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::ofstd PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/ofstd.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/ofstd.dll"
  )

# Import target "DCMTK::oflog" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::oflog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::oflog PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/oflog.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/oflog.dll"
  )

# Import target "DCMTK::oficonv" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::oficonv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::oficonv PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/oficonv.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/oficonv.dll"
  )

# Import target "DCMTK::dcmdata" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmdata APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmdata PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmdata.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmdata.dll"
  )

# Import target "DCMTK::i2d" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::i2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::i2d PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/i2d.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/i2d.dll"
  )

# Import target "DCMTK::dcmxml" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmxml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmxml PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmxml.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmxml.dll"
  )

# Import target "DCMTK::dcmimgle" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmimgle APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmimgle PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmimgle.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmimgle.dll"
  )

# Import target "DCMTK::dcmimage" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmimage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmimage PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmimage.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmimage.dll"
  )

# Import target "DCMTK::dcmjpeg" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmjpeg PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmjpeg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmjpeg.dll"
  )

# Import target "DCMTK::ijg8" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::ijg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::ijg8 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/ijg8.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/ijg8.dll"
  )

# Import target "DCMTK::ijg12" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::ijg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::ijg12 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/ijg12.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/ijg12.dll"
  )

# Import target "DCMTK::ijg16" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::ijg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::ijg16 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/ijg16.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/ijg16.dll"
  )

# Import target "DCMTK::dcmjpls" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmjpls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmjpls PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmjpls.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmjpls.dll"
  )

# Import target "DCMTK::dcmtkcharls" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmtkcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmtkcharls PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmtkcharls.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmtkcharls.dll"
  )

# Import target "DCMTK::dcmtls" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmtls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmtls PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmtls.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmtls.dll"
  )

# Import target "DCMTK::dcmnet" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmnet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmnet PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmnet.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmnet.dll"
  )

# Import target "DCMTK::dcmsr" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmsr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmsr PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmsr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmsr.dll"
  )

# Import target "DCMTK::cmr" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::cmr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::cmr PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/cmr.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/cmr.dll"
  )

# Import target "DCMTK::dcmdsig" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmdsig APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmdsig PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmdsig.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmdsig.dll"
  )

# Import target "DCMTK::dcmwlm" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmwlm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmwlm PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmwlm.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmwlm.dll"
  )

# Import target "DCMTK::dcmqrdb" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmqrdb APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmqrdb PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmqrdb.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmqrdb.dll"
  )

# Import target "DCMTK::dcmpstat" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmpstat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmpstat PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmpstat.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmpstat.dll"
  )

# Import target "DCMTK::dcmrt" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmrt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmrt PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmrt.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmrt.dll"
  )

# Import target "DCMTK::dcmiod" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmiod APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmiod PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmiod.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmiod.dll"
  )

# Import target "DCMTK::dcmfg" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmfg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmfg PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmfg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmfg.dll"
  )

# Import target "DCMTK::dcmseg" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmseg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmseg PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmseg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmseg.dll"
  )

# Import target "DCMTK::dcmtract" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmtract APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmtract PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmtract.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmtract.dll"
  )

# Import target "DCMTK::dcmpmap" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmpmap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmpmap PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmpmap.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmpmap.dll"
  )

# Import target "DCMTK::dcmect" for configuration "RelWithDebInfo"
set_property(TARGET DCMTK::dcmect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DCMTK::dcmect PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/lib/RelWithDebInfo/dcmect.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/cybermed/daddy/dependency/dcmtk-DCMTK-3.6.8/build_msvc/bin/RelWithDebInfo/dcmect.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
